[package]
name = "rustmap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.36", features = ["cargo"]}
rayon = "1.10.0"
tokio = {version = "1.44.2",features = ["full"]}
futures = "0.3.31"